<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchtype-partner</name>
   <tag></tag>
   <elementGuidId>96e8d2d6-4b39-4056-8c65-89aad839bf9b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-typeahead-partner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchtype-partner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Partner...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideNav&quot;)/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;slimScroll&quot;]/ul[@class=&quot;sublevel&quot;]/li[@class=&quot;in-search open&quot;]/ul[1]/div[@class=&quot;inline-search&quot;]/div[@class=&quot;typeahead__container cancel&quot;]/div[@class=&quot;typeahead__field&quot;]/span[@class=&quot;typeahead__query&quot;]/input[@class=&quot;js-typeahead-partner&quot;]</value>
   </webElementProperties>
</WebElementEntity>
