<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_jtestpartner1</name>
   <tag></tag>
   <elementGuidId>e2d1fa4f-c943-4a01-ab67-712f6ca258c2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead__display</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jtestpartner1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideNav&quot;)/div[@class=&quot;slimScrollDiv&quot;]/div[@class=&quot;slimScroll&quot;]/ul[@class=&quot;sublevel&quot;]/li[@class=&quot;in-search open&quot;]/ul[1]/div[@class=&quot;inline-search&quot;]/div[@class=&quot;typeahead__container cancel result&quot;]/div[@class=&quot;typeahead__result&quot;]/ul[@class=&quot;typeahead__list&quot;]/li[@class=&quot;typeahead__item typeahead__group-organization&quot;]/a[1]/span[@class=&quot;typeahead__display&quot;]</value>
   </webElementProperties>
</WebElementEntity>
